---
- name: Add new users and append the sudo users's group
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: sudo
    #generate_ssh_key: yes
    #ssh_key_bits: 2048
    #ssh_key_file: .ssh/id_rsa
  with_items:
    - "{{ users_list }}"
