---
- name: Add new users and append the sudo users's group
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: sudo
    #generate_ssh_key: yes
    #ssh_key_bits: 2048
    #ssh_key_file: .ssh/id_rsa
  with_items:
    - "{{ users_list }}"

- name: Make sure we have a 'jedimaster' group
  group:
    name: jedimaster
    state: present

- name: Allow 'jedimaster' group for passwordless
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%jedimaster'
    line: '%jedimaster ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to jedimaster group
  user: name="{{ item.name }}" groups=jedimaster append=yes state=present createhome=yes
  with_items:
    - "{{ users_list }}"

- name: Set up authorized keys for the jedimaster user list
  authorized_key: user="{{ item.name }}" key="{{ lookup('file', '{{ item.name }}.pub') }}"
  with_items:
    - "{{ users_list }}"
